<?php

declare(strict_types=1);

namespace Siganushka\MediaBundle\Tests\Storage;

use PHPUnit\Framework\TestCase;
use Siganushka\MediaBundle\Storage\LocalStorage;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\UrlHelper;
use Symfony\Component\Routing\RequestContext;

class LocalStorageTest extends TestCase
{
    protected LocalStorage $storage;
    protected Filesystem $filesystem;

    protected function setUp(): void
    {
        $requestStack = new RequestStack();
        $requestContext = new RequestContext();

        $this->storage = new LocalStorage(new UrlHelper($requestStack, $requestContext), sys_get_temp_dir());
        $this->filesystem = new Filesystem();
    }

    public function testAll(): void
    {
        $file1 = $this->filesystem->tempnam(sys_get_temp_dir(), 'test_');
        $file2 = $this->filesystem->tempnam(sys_get_temp_dir(), 'test_');

        $url1 = $this->storage->save($file1);
        static::assertFileDoesNotExist($file1);
        static::assertSame(\sprintf('http://localhost/uploads/%s', pathinfo($file1, \PATHINFO_BASENAME)), $url1);

        $url2 = $this->storage->save($file2, 'foo/bar/baz');

        static::assertFileDoesNotExist($file2);
        static::assertSame('http://localhost/uploads/foo/bar/baz', $url2);

        $this->storage->delete($url1);
        $this->storage->delete($url2);

        // Remove dir generated by tests
        $this->filesystem->remove(\sprintf('%s/uploads', sys_get_temp_dir()));
    }
}
